# Generated by Django 4.0.5 on 2022-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_category_item_description_item_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
