# Generated by Django 4.0.5 on 2022-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_image1_item_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
